[workspace]

[package]
name = "example"
version = "0.1.0"
authors = ["bam5wi <Martin.Bammer2@at.bosch.com>"]
edition = "2018"

[dependencies]
com = "0.1"
winapi = "0.3"
widestring = "0.4"
ole32-sys = "0.2"
bitflags = "1.2"
fltk = "0.5.1"
