[workspace]

[package]
name = "example"
version = "0.1.1"
authors = ["bam5wi <Martin.Bammer2@at.bosch.com>"]
edition = "2021"

[dependencies]
com = "0.6"
winapi = "0.3"
widestring = "1.0"
ole32-sys = "0.2"
bitflags = "1.3"
fltk = "1.3"
